name: Docker Image CI

on:
  push:
    branches: [ "master", "andrewald-patch-1" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: mobimedia/fury:latest,mobimedia/fury:$(date +"%y-%m-%d.%H-%M")
